### ISSUE TITLE
incorporate ingest session metadata into response json

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#162] opened 2020-10-19 17:52 UTC
Estimate: .5 days

**Comment by cyork** [comment] 2020-10-22 17:37
https://docs.google.com/document/d/1HKCXm6AiqAf7s96YSFiHqbgbdZbQUB7a745tCrfEP1E/edit#

**Comment by htpvu** [comment] 2020-12-01 16:07
duplicate of #159

**Closed as completed by htpvu** 2020-12-01 16:07 UTC
Labels: ingest, Ingest Session Index
