### ISSUE TITLE
Create checklist of items to check after spinning up instance

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#347] opened 2021-05-18 19:48 UTC
Part of Tasks planning for pilot implementation are written up here [https://docs.google.com/document/d/1vUIRzi_kTVaorz3-aVSaGBk-xpxASqYGkvAoz8NsNmg/edit# ](https://docs.google.com/document/d/1vUIRzi_kTVaorz3-aVSaGBk-xpxASqYGkvAoz8NsNmg/edit# )

**Comment by htpvu** [comment] 2021-05-24 18:11
duplicate of this https://github.com/jhu-idc/iDC-general/issues/349

**Closed as completed by htpvu** 2021-05-24 18:11 UTC
Labels: kubernetes pilot
