### ISSUE TITLE
Set up env for STAGE

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#248] opened 2020-12-08 19:18 UTC
- [x] SAML config (no blocker) 
- [x] Set up DNS - kubernetes manifest (will use mock infrastructure initially)
- [x] Set up storage bucket (Drupal, indexer) - kubernetes manifest 
- [x] Setup load balancer (entry point to the application) - controlled and created by k8s
- [x] THEN Set up http certificate
- [x] Figure out and Setup storage for saml secrets (collab with dev) 
- [x] Create Overlays (which translate local k8s manifest to cloud-appropriate k8s manifests) 0.5 day/env
- [x] DONE +0.5 day contingency 
- [x] Each new env requires addition Overlays for that env ~.5day

**Comment by derekbelrose** [comment] 2020-12-08 20:19
SAML config has been submitted to IT@JH

**Comment by derekbelrose** [comment] 2021-01-05 15:51
The terraform has been created to create storage, load balancers. They arent up because they are created when the kubernetes stack is created.

**Comment by htpvu** [comment] 2021-04-22 18:10
We will be using this instance for
- migration testing
- usability testing 

this instance is expected to be more staple thanthe TEST instance, which is subject to frequent updatesvis CI/CD

**Comment by jhujasonw** [comment] 2021-04-27 16:47
Requires the following tickets:

- [x] https://github.com/jhu-idc/idcApp-k8s/issues/40
- [x] https://github.com/jhu-idc/idcApp-k8s/issues/41
- [x] https://github.com/jhu-idc/idcApp-k8s/issues/42
- [x] https://github.com/jhu-idc/idcApp-k8s/issues/49

**Comment by jhujasonw** [comment] 2021-04-29 12:21
Blocked by ~~https://github.com/jhu-idc/idcApp-k8s/issues/43~~ https://github.com/jhu-idc/idcApp-k8s/issues/49

**Comment by jhujasonw** [comment] 2021-06-10 20:47
Stage instance is up in the cloud can @birkland and/or anyone else that would like to double check it please do so and let me know if I can close this.

**Comment by birkland** [comment] 2021-06-10 20:56
@jhujasonw  I couldn't successfully perform a search, it looks like the SOLR server URL needs to be updated?

Log in as admin and see:
https://stage.digital.library.jhu.edu/admin/config/search/search-api/server/default_solr_server

**Comment by jhujasonw** [comment] 2021-06-10 21:08
What ENV VAR sets that value?  Currently `DEFAULT_SOLR_HOST=solr-service` is set on the deployment.

**Comment by birkland** [comment] 2021-06-10 21:09
I'll have to dig in tomorrow

**Comment by jhujasonw** [comment] 2021-06-10 21:11
There is also no mention of it on the idc-isle-dc repo page and nothing in the https://github.com/jhu-idc/idc-isle-dc/blob/development/docker-compose.env.yml file

**Comment by jhujasonw** [comment] 2021-06-10 21:36
DRUPAL_DEFAULT_SOLR_HOST is the right env var

**Comment by birkland** [comment] 2021-06-10 21:42
Confirmed search works now.  All manual tests pass!

**Closed as completed by birkland** 2021-06-10 21:42 UTC
Labels: cloud
